day16homework/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from host_manage import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.login),
    url(r'^logout/$', views.logout),
    url(r'^create/$', views.create),
    url(r'^index/', include('host_manage.urls')),
]

host_manage/urls.py
#!/usr/bin/env python
"""day16homework URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from host_manage import views

urlpatterns = [
    url(r'^$', views.index),
    url(r'^del', views.delete),
    url(r'^edit(\d+)', views.edit),
    url(r'^re_edit_(\d+)', views.re_edit),
    url(r'^lob_back', views.lob_back),
    url(r'^add', views.add),
    url(r'^re_add', views.re_add),
    url(r'^lob', views.lob),
    url(r'^upload/$', views.upload),
]

host_manage/models.py
from django.db import models

# Create your models here.


class User_msg(models.Model):
    name = models.CharField(max_length=30)
    username = models.CharField(max_length=30)
    password = models.CharField(max_length=60)
    u_h = models.ManyToManyField("Host")

    def __str__(self):
        return self.username


# 业务线ORM
class LOB(models.Model):
    title = models.CharField(max_length=20)

    def __str__(self):
        return self.title


class Host(models.Model):
    ip = models.CharField(max_length=15)
    port = models.IntegerField()
    host_user = models.CharField(max_length=30)
    host_password = models.CharField(max_length=30)
    lob = models.ForeignKey('LOB', null=True)

    def __str__(self):
        return self.ip

templates/add.html
{% extends 'base.html' %}
{% block bd1 %}



<div class="row">
  <div class="col-md-4"></div>
  <div class="col-md-4 ">
      <form action="/index/re_add/" method="post" novalidate>
          <label for="recipient-name" class="control-label">新业务线:</label>
          <br>
          <span class="label label-warning">{{ obj.errors.new_lob.0 }}</span>
            {{ obj.new_lob }}

          <label for="recipient-name" class="control-label">服务器IP:</label>
            <br>
          <span class="label label-warning">{{ obj.errors.ip.0 }}</span>
          {{ obj.ip }}
          <label for="recipient-name" class="control-label">服务器端口:</label>
            <br>
          <span class="label label-warning">{{ obj.errors.port.0 }}</span>
          {{ obj.port }}
          <label for="recipient-name" class="control-label">服务器用户名:</label>
            <br>
          <span class="label label-warning">{{ obj.errors.username.0 }}</span>
          {{ obj.username }}
          <label for="recipient-name" class="control-label">服务器密码:</label>
            <br>
          <span class="label label-warning" >{{ obj.errors.password.0 }}</span>
          {{ obj.password }}



        <a class="btn btn-default" href="/index/lob_back/" data-dismiss="modal">结束</a>
        <button type="submit" class="btn btn-primary" id="edit-send">提交</button>
         <h4 style="color: darkred">{{ error }}</h4>


          </form>
    </div>
  </div>



{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% include 'css_js.html' %}
    <style>
        body {
            margin: 0;
            font-family: 微软雅黑, 华文细黑, 黑体, Arial;
        }

        .pg-header {
            height: 48px;
            background: cadetblue;
            /**/
            line-height: 48px;
        }

        .pg-header .logo {
            width: 200px;
            background-color: burlywood;
            text-align: center;
            font-size: 26px;
            color: white;
            font-family: 微软雅黑, 华文细黑, 黑体, Arial;
        }

        .pg-body .menus {
            position: absolute;
            top: 48px;
            /*贴着左边*/
            left: 0;
            /*贴着下面*/
            bottom: 0;
            width: 200px;
            /*background-color: red;*/
        }

        .item .title {
            color: white;
            text-align: center;
            height: 40px;
            background-color: cadetblue;
            line-height: 40px;
            border-radius: 10px;
            border-bottom: 3px solid transparent;
        }

        .item .title:hover {
            border-bottom: 3px solid rebeccapurple;
        }

        .item .menu-content a {
            text-align: center;
            display: block;
        }

        .pg-body .content .content-letf {
            position: absolute;
            top: 53px;
            left: 214px;
            /*bottom: 0;*/
            right: 1%;
            /*margin-right: 10px;*/
            border: 2px solid #EDEDED;
        }

        .pg-body .content .content-right {
            position: absolute;
            top: 53px;
            left: 51%;
            /*bottom: 0;*/
            right: 10px;
            /*margin-left: 10px;*/
            border: 2px solid #EDEDED;

        }

        .left {
            float: left;
        }

        .right {
            float: right;
        }
    </style>
</head>
<body>
<div class='pg-header'>

    <div class="row">
        <div class="col-xs-6 col-md-4">
            <div class="logo left">运维平台</div>
        </div>
        <div class="col-xs-6 col-md-6"></div>
        <div class="col-xs-6 col-md-2">
            <div class="dropdown">
                <button class="btn btn-info dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="true">
                    用户
                    <span class="caret"></span>
                </button>
                <ul class="dropdown-menu " aria-labelledby="dropdownMenu1">
                    <li><a href="/logout/">注销</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="dropdown">
        <a id="dLabel" data-target="#" href="http://example.com" data-toggle="dropdown" role="button"
           aria-haspopup="true" aria-expanded="false">
            Dropdown trigger
            <span class="caret"></span>
        </a>

        <ul class="dropdown-menu" aria-labelledby="dLabel">
            ...
        </ul>
    </div>
</div>

<div class='pg-body'>
    <div class="menus">
        <div class="item">
            <div class="title" id="m1">
                <a style="color: white" href="/index/">主页</a></div>
            <div class="title" id="m1">
                <a style="color: white" href="/index/lob/">业务线</a>
            </div>
            <div class="title" id="m1">
                <a style="color: white" href="/index/upload/">上传</a>
            </div>
        </div>
    </div>

    <div class="content">
        <div class="content-letf">
            {% block bd1 %}{% endblock %}
        </div>
        {#            <div class="content-right">#}
        {#                {% block bd2 %}{% endblock %}#}
        {#            </div>#}

    </div>
</div>
</body>
</html>

templates/css_js.html
    <link href="/static/css/bootstrap.css" rel="stylesheet">
    <script src="/static/jquery.js"></script>
    <script src="/static/js/bootstrap.js"></script>

templates/edit.html
{% extends 'base.html' %}
{% block bd1 %}



    <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4 ">
            <form action="/index/re_edit_{{ hid }}" method="post">
                <label for="recipient-name" class="control-label">业务线:</label>
{#                <input type="text" name="lob" class="form-control" id="edit-lob" value="{{ lob }}">#}
{#                <input type="hidden" name="id" class="tmpid" value="{{ hid }}" id="edit-id">#}
                {{ obj.lob_id }}

                <a class="btn btn-default" href="/index/lob_back/" data-dismiss="modal">结束</a>
                <button type="submit" class="btn btn-primary" id="edit-send">提交</button>
                <h4 style="color: darkred">{{ error }}</h4>
            </form>
        </div>
    </div>



{% endblock %}

templates/host.html
{% extends 'base.html' %}

{% block bd1 %}
    <h1>host 多表连查</h1>
    <h2>
        <p>{{ username }}所管理IP</p>
        {% for obj in user_ip %}
            <p>ip:{{ obj }}</p>
        {% endfor %}
    </h2>
    <p>原生sql:
    select host_id,ip from host_manage_user_msg
    left join host_manage_user_msg_uh on host_manage_user_msg.id=host_manage_user_msg_uh.user_msg_id left join host_manage_host on host_id=host_manage_host.id where username='wang';</p>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% block bd1 %}
    <div style="width: 1000px; margin: 0 auto">
        <h2>
            <p>用户： {{ username }}</p>
        </h2>
        <div class="table-responsive">
            <table class="table  table-hover">
                <thead>
                <tr>
                    <th>IP地址</th>
                    <th>服务器端口</th>
                    <th>服务器用户名</th>
                    <th>服务器密码</th>
                    <th>LOB业务线</th>
                    {#            <th>操作</th>#}
                </tr>
                </thead>

                {% for foo in host_l %}
                    <tr>
                        <td>{{ foo.ip }}</td>
                        <td>{{ foo.port }}</td>
                        <td>{{ foo.host_user }}</td>
                        <td>{{ foo.host_password }}</td>
                        <td>{{ foo.lob.title }}</td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    <div style="text-align:center;">
        <nav aria-label="..." >
            <ul class="pagination">
                {{ page_info.page_str | safe }}
            </ul>
        </nav>
    </div>
    </div>
{% endblock %}

templates/lob.html
{% extends 'base.html' %}
{% block bd1 %}
    <div style="width: 1000px; margin: 0 auto">
        <div class="table-responsive">
            <table class="table  table-hover">
                <thead>
                <tr>
                    {#                <th>id</th>#}
                    <th>LOB业务线</th>
                    <th>IP地址</th>
                    <th>
                        {#                模态框按钮#}
                        <button type="button" class="btn btn-info btn-sm" data-toggle="modal"
                                data-target="#exampleModal">
                            添加
                        </button>
                        &nbsp;操作

                    </th>
                    <th><a class="btn btn-info btn-sm" href="/index/re_add">添加</a>
                        &nbsp;Interface 2

                    </th>
                </tr>
                </thead>

                {% for foo in lob_l %}
                    <tr>

                        {#                    <td target="id">{{ foo.id }}</td>#}
                        <td target="lob">{{ foo.lob.title }}</td>
                        <td target="ip">{{ foo.ip }}</td>

                        <td>
                            <button type="button" class="btn btn-warning" data-toggle="modal"
                                    data-target="#exampleModal1"
                                    data-whatever={{ foo.id }} data-id={{ foo.lob.id }}>
                                编辑
                            </button>

                            <a href="/index/del?id={{ foo.id }}" class="btn btn-danger">删除</a>

                        </td>
                        <td>
                            <a class="btn btn-warning"
                               href="/index/re_edit_{{ foo.id }}">编辑</a>
                        </td>
                    </tr>
                {% endfor %}


            </table>
        </div>
        <div style="text-align:center;">
            <nav aria-label="...">
                <ul class="pagination">
                    {{ page_info.page_str | safe }}
                </ul>
            </nav>
        </div>
    </div>
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="exampleModalLabel">添加</h4>
                </div>
                <div class="modal-body">


                    {#                        <div style="display: none" id="add-alert" class="alert alert-danger" role="alert">...</div>#}
                    <label for="recipient-name" class="control-label">新业务线:</label>
                    <br>
                    <span class="label label-warning" id="id_alert_new_lob">{{ obj.errors.new_lob.0 }}</span>
                    {{ add_form_obj.new_lob }}
                    <label for="recipient-name" class="control-label">服务器IP:</label>
                    <br>
                    <span class="label label-warning" id="id_alert_ip">{{ obj.errors.ip.0 }}</span>
                    {{ add_form_obj.ip }}
                    <label for="recipient-name" class="control-label">服务器端口:</label>
                    <br>
                    <span class="label label-warning" id="id_alert_port">{{ obj.errors.port.0 }}</span>
                    {{ add_form_obj.port }}
                    <label for="recipient-name" class="control-label">服务器用户名:</label>
                    <br>
                    <span class="label label-warning" id="id_alert_username">{{ obj.errors.username.0 }}</span>
                    {{ add_form_obj.username }}
                    <label for="recipient-name" class="control-label">服务器密码:</label>
                    <br>
                    <span class="label label-warning" id="id_alert_password">{{ obj.errors.password.0 }}</span>
                    {{ add_form_obj.password }}

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">结束</button>
                    <button id="add-btn" type="button" class="btn btn-primary">提交</button>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="exampleModal1" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="exampleModalLabel">编辑</h4>
                </div>
                <div class="modal-body">

                    <div class="form-group">
                        {#              提示框#}
                        <div style="display: none" id="test" class="alert alert-danger" role="alert">...</div>
                        <label for="recipient-name" class="control-label">业务线:</label>
                        {#                        <input type="text" name="lob" class="form-control" id="edit-lob">#}
                        <input type="hidden" class="tmpid" value="" id="id_ip_id">
                        {{ edit_form_obj.lob_id }}
                    </div>


                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">结束</button>
                    <button type="button" class="btn btn-primary" id="edit-send">提交</button>
                </div>
            </div>
        </div>
    </div>
    <script>
        {#        $('#exampleModal').on('show.bs.modal', function (event) {#}
        {#            var button = $(event.relatedTarget) // Button that triggered the modal#}
        {#            var recipient = button.data('whatever')#}
        {#            // Extract info from data-* attributes#}
        {#            // If necessary, you could initiate an AJAX request here (and then do the updating in a callback).#}
        {#            // Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.#}
        {#            var modal = $(this)#}
        {#  modal.find('.modal-title').val(this.val())#}
        {#            modal.find('.modal-body input').val(recipient)#}
        {#        });#}

        $('#exampleModal1').on('show.bs.modal', function (event) {
            var button = $(event.relatedTarget)
            var recipient = button.data('whatever')
            var recipient1 = button.data('id')
            var modal = $(this)
            modal.find("option[value=" + recipient1 + "]").attr('selected', "selected");
            modal.find('#id_ip_id').val(recipient)
        });
        $(function () {
            bindBtn();
            bindAdd();
        });
        function bindAdd() {
            $('#add-btn').click(function () {

                var lob = $('#id_new_lob').val();
                var ip = $("#id_ip").val();
                var port = $("#id_port").val();
                var user = $("#id_username").val();
                var pwd = $("#id_password").val();
                $.ajax({
                    url: '/index/add/',
                    type: "POST",
                    data: {ip: ip, new_lob: lob, port: port, username: user, password: pwd},
                    dataType: 'json',
                    success: function (data) {
                        if (data.status) {
                            location.href = "/index/lob/";
                        } else {
                            {#                            $('#add-alert').css('display', 'block');#}
                            $('#id_alert_new_lob').text(data.error.new_lob);
                            $('#id_alert_ip').text(data.error.ip);
                            $('#id_alert_port').text(data.error.port);
                            $('#id_alert_username').text(data.error.username);
                            $('#id_alert_password').text(data.error.password);
                        }
                    }
                })
            })
        }

        function bindBtn() {
            $('#edit-send').click(function () {

                var hid = $('#id_ip_id').val();
                var lob = $("#id_lob_id").val();
                console.log(hid, lob)
                $.ajax({
                    url: '/index/edit' + hid,
                    type: "POST",
                    data: {lob_id: lob},
                    dataType: 'json',
                    success: function (data) {
                        if (data.status) {
                            location.href = "/index/lob/";
                        }
                    }
                })
            })
        }
    </script>

    <script>
        $(function () {
            $('#exampleModal1').modal('hide')
        });
        $(function () {
            $('#exampleModal').modal('hide')
        });
    </script>
    <script>
        $(function () {
            $('#exampleModal1').on('hide.bs.modal', function () {
                $('#test').css('display', 'none');
            })
        });
        $(function () {
            $('#exampleModal').on('hide.bs.modal', function () {
                $('#id_alert_new_lob').text('');
                $('#id_alert_ip').text('');
                $('#id_alert_port').text('');
                $('#id_alert_username').text('');
                $('#id_alert_password').text('');
            })
        });
    </script>
{% endblock %}

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% include 'css_js.html' %}
    <style>
        body {
            margin-top: 15%;
        }
    </style>
</head>
<body>


<div class="container-fluid">

    <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4 ">

            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">主机管理系统</h3>
                </div>

                <div class="panel-body">
                    <div class="form-group">
                        <label for="inputEmail3" class="col-sm-2 control-label">用户名</label>
                        <div class="col-sm-10">
                            {{ login_form_obj.username }}
                            <span class="label label-warning" id="id_alert_username">{{ obj.errors.new_lob.0 }}</span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputPassword3" class="col-sm-2 control-label">密码</label>
                        <div class="col-sm-10">
                            {#                            <input type="password" class="form-control" id="inputPassword3" placeholder="Password">#}
                            {{ login_form_obj.password }}
                            <span class="label label-warning" id="id_alert_password">{{ obj.errors.new_lob.0 }}</span>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="button" id="but" class="btn btn-default popover-destroy">登录
                            </button>
                            {#        提示框，输入错误时修改display#}
                            <span class="label label-danger" id="id_error"></span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4"></div>
    </div>
</div>


</body>

<script>
    $(function () {
        bindBtn();
    });

    function bindBtn() {
        $('#but').click(function () {
            $('#id_alert_username').text('');
            $('#id_alert_password').text('');
            $('#id_error').text('');
            var u = $('#id_username').val();
            var p = $("#id_password").val();
            $.ajax({
                url: '/',
                type: "POST",
                data: {username: u, password: p},
                dataType: 'json',
                success: function (data) {
                    if (data.status) {
                        location.href = "/index/";
                    } else {
                        if (data.error) {
                            $('#test').css('display', 'block');
                            console.log(data.error)
                            $('#id_error').text(data.error);
                        } else {
                            console.log(data.obj)
                            $('#id_alert_username').text(data.obj.username);
                            $('#id_alert_password').text(data.obj.password);
                        }
                    }
                }
            })

        })
    }
</script>
</html>

templates/upload.html
{% extends 'base.html' %}
{% block bd1 %}
<form action="/index/upload/" method="post" enctype="multipart/form-data">
    <input type="file" name="test">
    <input type="submit" value="上传">
    {{ v }}
</form>
{% endblock %}